### PR TITLE
Added ACTUAL quotes to the etag.  #oops 

### PR DESCRIPTION
**Pull request by ctoestreich**
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19

### CODE REVIEW

**Comment by davydotcom** [comment]
thanks!

**Comment by ctoestreich** [comment]
After writing a specification for this I have another change for this.

**Comment by ctoestreich** [comment]
Adding more specs, hold from release for a few

**Comment by davydotcom** [comment]
yep thought so after i saw some things ;)

**Comment by davydotcom** [comment]
help is much appreciated

**Comment by ctoestreich** [comment]
I guess chrome && firefox must be forgiving with the absence of the quotes because it behaves the same, however most sites include the quote given that you can do the weak token reference which needs the quotes per the standards.

**Comment by davydotcom** [comment]
yea read the spec after you linked it.

**Pull request merged**
