### PR TITLE
Re-enable support for ADVANCED optimizations.

### PR DESCRIPTION
**Pull request by roadrunner2**
The "externs" support in the second commit is very basic - it would probably be good to expand it to allow patterns similar to the excludes and includes.

### CODE REVIEW

**Comment by davydotcom** [comment]
externs were intentionally omitted because they can't resolve things on the class path necessarily such as a Jar resolver

**Comment by roadrunner2** [comment]
Couldn't that be added later, though? I.e. starting with only being able to resolve externs that refer to files on the FS now, then allowing them to refer to entries in Jar's later would be backwards compatible.

Anyway, if you decide to not take this pull request, then I think you should at least A) document that the ADVANCED option is not supported, and B) maybe throw an exception instead of silently treating it as SIMPLE.

**Comment by davydotcom** [comment]
I don't mind adding advanced just don't think external makes sense done this way since the ap bundling handles that already

**Comment by davydotcom** [comment]
I added ADVANCED externs I'm working on can't merge do to a previous merge. Thanks for finding this.

**Pull request closed without merging**
