### PR TITLE
Adding Last-Modified header and code cleanup

### PR DESCRIPTION
**Pull request by ctoestreich**

### CODE REVIEW

**Comment by davydotcom** [comment]
not seeing where the last modified is in here besides spring boot

**Comment by davydotcom** [comment]
nm see what you did sweet

**Comment by davydotcom** [comment]
will actually release as 2.5.2 since 2.5.1 was already used for a grails plugin fix

**Comment by ctoestreich** [comment]
Cool.  Hopefully the sort issue clears up some of the concurrent list modification stuff that were were seeing.

**Pull request merged**
